### ISSUE TITLE
Can't save new multiBlock 

### ISSUE THREAD

**Issue by mapit75** [multicolor-rgb/multiBlock-for-bludit#1]
Can't save a new multiBlock when the bludit instance is built in a subfolder of the main domain.

https://{domainname.com}/{subfolder}/admin/plugins/multiBlock

After clicking save you get 404 error with redirection 

https://{domainname.com}/admin/plugins/multiBlock

**Comment by multicolor-rgb** [comment]
Hi! Thanks you want use it:) 
I hope this week i will make update and fix yours problem.

**Comment by mapit75** [comment]
Hi multi :) Any progress?

**Comment by multicolor-rgb** [comment]
Hi, yes - tommorow i will upload fixed release:)

**Comment by multicolor-rgb** [comment]
https://github.com/multicolor-rgb/multiBlock-for-bludit/archive/refs/heads/3.1.zip try now.

**Comment by mapit75** [comment]
Works fine thanks!
